#!/usr/bin/env python3
"""Bump package version via a PR that the release app fast-forwards itself.

Compatible with branch-protection rulesets that require all changes to land
through PRs and require commits to be signed:

0. If the configured version already has a merged bump commit on main but
   no release tag (a prior run failed between merge and tag), the missing
   tag is pushed and the run stops. Re-running cz in that state would
   double-bump.
1. ``cz bump --files-only`` updates ``.cz.toml`` (cz version field),
   ``package.json`` (via version_files), and ``CHANGELOG.md`` in the package
   directory; no local commit or tag.
2. A release-line-specific bump branch is created on the remote at the
   current target-branch tip via the REST refs API. A stale branch left by a
   failed prior run is force-moved to that tip instead of failing the run.
3. The bumped files are committed onto that branch via the GraphQL
   ``createCommitOnBranch`` mutation, which signs the commit as the
   authenticated bot identity.
4. A PR is opened so the bump has CI, a changelog entry and an audit trail.
   If an open PR for the branch already exists, it is reused.
5. The script waits for every check on the PR to conclude successfully. A
   PR whose checks have not registered yet reads as pending, never passing,
   so a fresh commit cannot slip through before Actions reports on it.
6. The script fast-forwards the target branch to the PR head with a strict
   (non-force) refs API update, performed by the release app. The
   require-review ruleset lists the app as a bypass actor, and GitHub only
   honours app bypass on direct ref updates, never on the merge API or
   auto-merge, so this is the one merge path that does not strand the PR
   waiting for a human review. Before updating, the PR's base SHA is
   compared against the live target branch: if the branch moved (seen by
   that guard, or by the strict update being refused), the bump branch is
   rebuilt on the new tip and its checks are awaited again.
7. GitHub marks the PR merged once its head is reachable from the base. The
   script verifies that, then creates and pushes the ``<version>-<package>``
   tag at the merged SHA. Tags trigger the existing ``publish.yml`` publish
   workflow. The bump branch is deleted once the tag is pushed.

The tag is the only thing that publishes a release, so it is created from a
verified merge and nothing else. If the checks fail, the fast-forward is
refused or the PR does not report merged, the job fails with the PR link
instead of forcing the ref or tagging an unmerged commit: a released version
that never landed on the target branch leaves the version file behind npm.
A PR that someone merges by hand while the script waits is adopted: the run
tags that merge commit and exits successfully instead of failing.

The runner needs ``GH_TOKEN`` in env: a GitHub App installation token with
contents write (branch and tag refs) and pull-requests write, generated by
the workflow for the release app.
"""

import argparse
import base64
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path


def run_command(cmd: list[str], cwd: str | None = None, env: dict | None = None) -> tuple[int, str, str]:
    """Run a command and return exit code, stdout, and stderr."""
    try:
        merged_env = os.environ.copy()
        if env:
            merged_env.update(env)
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=cwd,
            check=False,
            env=merged_env,
        )
        return result.returncode, result.stdout.strip(), result.stderr.strip()
    except Exception as e:
        return 1, "", str(e)


def configure_git() -> None:
    print("Configuring git...")
    run_command(["git", "config", "--local", "user.email", "action@github.com"])
    run_command(["git", "config", "--local", "user.name", "GitHub Action"])


def get_repo_slug() -> str:
    """Return ``owner/repo`` for the current checkout, e.g. ``keycardai/typescript-sdk``."""
    exit_code, stdout, _ = run_command(
        ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"]
    )
    if exit_code != 0 or not stdout:
        print("Failed to determine repository slug from gh CLI")
        sys.exit(1)
    return stdout


def get_branch_sha(branch: str) -> str:
    """Return the current commit SHA on an origin branch."""
    exit_code, stdout, stderr = run_command(["git", "rev-parse", f"origin/{branch}"])
    if exit_code != 0:
        print(f"Failed to read origin/{branch}: {stderr}")
        sys.exit(1)
    return stdout


def pull_branch(branch: str) -> bool:
    print(f"Pulling latest changes from origin/{branch}...")
    exit_code, _, stderr = run_command(["git", "fetch", "origin", branch])
    if exit_code != 0:
        print(f"Failed to fetch origin/{branch}: {stderr}")
        return False
    exit_code, _, stderr = run_command(
        ["git", "reset", "--hard", f"origin/{branch}"]
    )
    if exit_code != 0:
        print(f"Failed to reset to origin/{branch}: {stderr}")
        return False
    return True


def get_configured_version(package_dir: str) -> str | None:
    """Return the version cz has recorded for the package, or ``None``."""
    exit_code, stdout, stderr = run_command(
        ["cz", "version", "--project"], cwd=package_dir
    )
    if exit_code != 0 or not stdout.strip():
        print(f"Could not read configured version: {stderr}")
        return None
    return stdout.strip()


def tag_exists_on_remote(tag: str) -> bool:
    exit_code, stdout, _ = run_command(
        ["git", "ls-remote", "--tags", "origin", f"refs/tags/{tag}"]
    )
    return exit_code == 0 and bool(stdout.strip())


def recover_untagged_bump(repo: str, package_name: str, package_dir: str) -> bool | None:
    """Push the missing release tag for a bump that merged without one.

    A bump can land on the target branch without its tag when a run fails
    between the fast-forward and the tag step, or when a bump PR is merged by
    hand. That leaves the version files ahead of the last release tag with
    nothing to trigger the publish. When the configured version has a merged
    bump commit on the target branch but no tag, push the tag at that commit
    and stop.

    Returns ``True`` when the missing tag was pushed (the bump is complete),
    ``False`` when the tag push failed, and ``None`` when there is nothing
    to recover and the normal bump flow should proceed.
    """
    version = get_configured_version(package_dir)
    if version is None:
        return None
    tag = f"{version}-{package_name}"
    if tag_exists_on_remote(tag):
        return None

    headline = f"bump: {package_name} → {version}"
    exit_code, stdout, _ = run_command(
        ["git", "log", "--fixed-strings", f"--grep={headline}", "--format=%H", "-1", "HEAD"]
    )
    sha = stdout.strip()
    if exit_code != 0 or not sha:
        return None

    print(
        f"Version {version} has a merged bump commit ({sha[:8]}) but no {tag} tag; "
        "recovering the tag instead of bumping again."
    )
    if not create_and_push_tag(repo, tag, sha):
        return False
    print(f"Recovered: tag {tag} pushed.")
    return True


def cz_bump_files_only(
    package_dir: str, package_name: str, increment: str | None = None
) -> str | None:
    """Run ``cz bump --files-only`` and return the new version string.

    cz prints a line like ``bump: keycardai-oauth 0.4.0 → 0.5.0`` to stdout;
    we parse that for the new version. Returns ``None`` if cz failed or
    the version transition could not be determined (e.g. nothing to bump).
    """
    print(f"Running cz bump --files-only for {package_name}...")
    command = ["cz", "bump", "--changelog", "--yes", "--files-only"]
    if increment:
        command.extend(["--increment", increment.upper(), "--allow-no-commit"])
    exit_code, stdout, stderr = run_command(command, cwd=package_dir)

    if exit_code != 0:
        if "NO_COMMITS_TO_BUMP" in stderr or "no eligible commits" in stderr.lower():
            print("cz reports no eligible commits since last tag; nothing to bump.")
            return None
        print(f"cz bump failed (exit {exit_code}): {stderr}")
        sys.exit(1)

    print(stdout)

    match = re.search(r"\b(\d+\.\d+\.\d+)\s*(?:→|->|to)\s*(\d+\.\d+\.\d+)", stdout)
    if not match:
        print(f"Could not parse new version from cz output: {stdout}")
        sys.exit(1)
    return match.group(2)


def get_modified_files() -> list[str]:
    """Return the list of files changed in the working tree (relative paths)."""
    exit_code, stdout, stderr = run_command(["git", "diff", "--name-only"])
    if exit_code != 0:
        print(f"Failed to list modified files: {stderr}")
        sys.exit(1)
    return [line for line in stdout.splitlines() if line]


def bump_branch_name(target_branch: str, package_name: str, version: str) -> str:
    """Return a release-line-specific bump branch name.

    Namespacing by release line keeps a 1.x bump and a main bump of the same
    package from colliding on one branch ref.
    """
    release_line = re.sub(r"[^A-Za-z0-9._-]+", "-", target_branch)
    return f"bump/{release_line}/{package_name}-{version}"


def create_remote_branch(repo: str, branch: str, sha: str) -> bool:
    """Create the bump branch at ``sha``, reusing a stale one if it exists.

    A failed prior run leaves its bump branch behind, and re-running the job
    computes the same version and therefore the same branch name. An existing
    ref is force-moved to the intended SHA instead of failing the run. Only
    bump branches are ever force-moved; the target branch is only ever
    fast-forwarded.
    """
    print(f"Creating remote branch {branch} at {sha[:8]}...")
    exit_code, _, stderr = run_command(
        [
            "gh",
            "api",
            f"repos/{repo}/git/refs",
            "-X",
            "POST",
            "-f",
            f"ref=refs/heads/{branch}",
            "-f",
            f"sha={sha}",
        ]
    )
    if exit_code == 0:
        return True
    if "already exists" not in stderr.lower():
        print(f"Failed to create remote branch: {stderr}")
        return False

    print(
        f"Branch {branch} already exists (stale from a prior run); "
        f"force-moving it to {sha[:8]}..."
    )
    exit_code, _, stderr = run_command(
        [
            "gh",
            "api",
            "-X",
            "PATCH",
            f"repos/{repo}/git/refs/heads/{branch}",
            "-f",
            f"sha={sha}",
            "-F",
            "force=true",
        ]
    )
    if exit_code != 0:
        print(f"Failed to move existing branch {branch}: {stderr}")
        return False
    return True


def delete_remote_branch(repo: str, branch: str) -> None:
    """Delete the bump branch. Best-effort: the release is already complete."""
    print(f"Deleting branch {branch}...")
    exit_code, _, stderr = run_command(
        ["gh", "api", "-X", "DELETE", f"repos/{repo}/git/refs/heads/{branch}"]
    )
    if exit_code != 0:
        print(f"Could not delete branch {branch} (continuing): {stderr}")


def create_signed_commit_on_branch(
    repo: str,
    branch: str,
    parent_sha: str,
    files: list[str],
    headline: str,
    body: str,
) -> bool:
    """Submit a signed commit to ``branch`` via the GraphQL
    ``createCommitOnBranch`` mutation.

    Each file's current working-tree content is base64-encoded and sent as
    a file addition. The commit is signed by GitHub as the authenticated
    user (the bot identity owning ``GH_TOKEN``).
    """
    print(f"Creating signed commit on {branch} via GraphQL mutation...")

    additions = []
    for path in files:
        content = Path(path).read_bytes()
        additions.append(
            {
                "path": path,
                "contents": base64.b64encode(content).decode("ascii"),
            }
        )

    mutation = (
        "mutation($input: CreateCommitOnBranchInput!) {"
        "  createCommitOnBranch(input: $input) {"
        "    commit { oid url }"
        "  }"
        "}"
    )
    request_body = {
        "query": mutation,
        "variables": {
            "input": {
                "branch": {"repositoryNameWithOwner": repo, "branchName": branch},
                "expectedHeadOid": parent_sha,
                "fileChanges": {"additions": additions},
                "message": {"headline": headline, "body": body},
            }
        },
    }

    # gh api graphql --input <file> is the path that accepts a fully-formed
    # request body. --raw-field variables=... does not preserve nested JSON.
    with tempfile.NamedTemporaryFile(
        "w", suffix=".json", delete=False
    ) as tmp:
        json.dump(request_body, tmp)
        tmp_path = tmp.name

    try:
        exit_code, stdout, stderr = run_command(
            ["gh", "api", "graphql", "--input", tmp_path]
        )
    finally:
        os.unlink(tmp_path)

    if exit_code != 0:
        print(f"GraphQL createCommitOnBranch failed: {stderr}")
        return False

    try:
        payload = json.loads(stdout)
        if "errors" in payload:
            print(f"GraphQL returned errors: {payload['errors']}")
            return False
        oid = payload["data"]["createCommitOnBranch"]["commit"]["oid"]
        print(f"Created signed commit {oid[:8]} on {branch}")
    except (json.JSONDecodeError, KeyError) as e:
        print(f"Unexpected GraphQL response shape: {stdout} ({e})")
        return False
    return True


def wait_for_pr_stable(pr_number: int, timeout_seconds: int = 120) -> bool:
    """Poll mergeStateStatus until GitHub has a definite state for the PR.

    A freshly opened PR, and a bump branch that was just rebuilt, start as
    UNKNOWN or UNSTABLE while GitHub computes mergeability. This is a
    settling delay, not the checks gate: :func:`checks_verdict` treats an
    unregistered rollup as pending, so a commit can never merge before its
    checks appear. A PR that is not OPEN returns immediately; the caller's
    next read handles MERGED or CLOSED.
    """
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        exit_code, stdout, _ = run_command(
            ["gh", "pr", "view", str(pr_number), "--json", "state,mergeStateStatus"]
        )
        if exit_code == 0:
            data = json.loads(stdout)
            if data.get("state") != "OPEN":
                return True
            state = data.get("mergeStateStatus", "")
            print(f"PR #{pr_number} merge state: {state}")
            if state not in ("UNKNOWN", "UNSTABLE"):
                return True
        time.sleep(5)
    print(f"Timed out waiting for PR #{pr_number} to reach a stable merge state")
    return False


def create_bump_pr(
    branch: str, target_branch: str, package_name: str, new_version: str
) -> int | None:
    """Open a PR for the bump branch, reusing an open one if it exists.

    A failed prior run can leave its PR open; gh refuses to create a second
    PR for the same head and prints the existing PR's URL, which is adopted.
    Returns the PR number on success, ``None`` on failure.
    """
    title = f"bump: {package_name} → {new_version}"
    pr_body = (
        f"Auto-bump for `{package_name}` to `{new_version}`.\n\n"
        "Generated by `scripts/bump_package.py`. Once the checks pass, the "
        "release app fast-forwards the target branch to this PR's head "
        "under its ruleset bypass, then creates the release tag at that "
        "SHA, which triggers the publish workflow."
    )

    print(f"Opening PR for {branch}...")
    exit_code, stdout, stderr = run_command(
        [
            "gh",
            "pr",
            "create",
            "--head",
            branch,
            "--base",
            target_branch,
            "--title",
            title,
            "--body",
            pr_body,
        ]
    )
    if exit_code != 0:
        existing = re.search(r"/pull/(\d+)", stderr)
        if not existing:
            print(f"Failed to create PR: {stderr}")
            return None
        pr_number = int(existing.group(1))
        print(f"Reusing existing open PR #{pr_number} for {branch}.")
    else:
        pr_url = stdout.strip().splitlines()[-1]
        pr_number_match = re.search(r"/pull/(\d+)", pr_url)
        if not pr_number_match:
            print(f"Could not parse PR number from gh output: {pr_url}")
            return None
        pr_number = int(pr_number_match.group(1))
        print(f"Opened PR #{pr_number}: {pr_url}")

    if not wait_for_pr_stable(pr_number):
        return None
    return pr_number


OK_CONCLUSIONS = {"SUCCESS", "NEUTRAL", "SKIPPED"}


def check_name(check: dict) -> str:
    """Name a rollup entry: check runs carry ``name``, statuses ``context``."""
    return check.get("name") or check.get("context") or "<unnamed check>"


def checks_verdict(pr_data: dict) -> tuple[str, str | None]:
    """Summarise the PR's status rollup as ``SUCCESS``, ``PENDING`` or
    ``FAILURE``, plus the name of the check that decided a non-success verdict.

    Every check on the PR must succeed, required or not. That is deliberately
    conservative for a gate that merges under ruleset bypass: a failure in an
    optional check aborts the bump, and a re-run retries it.

    ``FAILURE`` wins over ``PENDING``: one failed check sinks the bump even
    while others are still running. An empty rollup is ``PENDING``, never
    success: right after a commit is created, Actions has not registered its
    check runs yet (and a token without checks read sees nothing at all);
    reading that emptiness as success would merge an untested commit. The
    pending state is bounded by the caller's timeout.
    """
    rollup = pr_data.get("statusCheckRollup") or []
    if not rollup:
        return "PENDING", None
    verdict = "SUCCESS"
    blocker: str | None = None
    for check in rollup:
        status = (check.get("status") or "").upper()
        conclusion = (check.get("conclusion") or "").upper()
        if conclusion and conclusion not in OK_CONCLUSIONS:
            return "FAILURE", check_name(check)
        if (status and status != "COMPLETED") or (not status and not conclusion):
            verdict = "PENDING"
            blocker = check_name(check)
    return verdict, blocker


def pr_url(repo: str, pr_number: int) -> str:
    return f"https://github.com/{repo}/pull/{pr_number}"


def read_pr(pr_number: int, fields: str) -> dict | None:
    exit_code, stdout, stderr = run_command(
        ["gh", "pr", "view", str(pr_number), "--json", fields]
    )
    if exit_code != 0:
        print(f"Failed to read PR #{pr_number}: {stderr}")
        return None
    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        print(f"Could not parse PR JSON: {stdout}")
        return None


def wait_for_checks(
    repo: str,
    pr_number: int,
    timeout_seconds: int = 1200,
    poll_seconds: int = 30,
) -> dict | None:
    """Wait for every check on the PR to conclude successfully.

    Returns ``{"head": sha}`` with the head SHA the checks ran against, or
    ``{"merged": sha}`` when the PR merged while waiting (someone else landed
    the bump; only the tag is still owed). Returns ``None`` if any check
    fails, the PR is closed without merging, or the timeout elapses. Pending
    checks (including a rollup with no registered checks) are never treated
    as passing: the caller must not merge on ``None``.
    """
    print(f"Waiting for checks on PR #{pr_number} (timeout {timeout_seconds}s)...")
    deadline = time.time() + timeout_seconds
    last_verdict = None

    while True:
        data = read_pr(pr_number, "state,headRefOid,statusCheckRollup,mergeCommit")
        if data is not None:
            state = data.get("state")
            if state == "MERGED":
                sha = (data.get("mergeCommit") or {}).get("oid")
                if sha:
                    print(
                        f"PR #{pr_number} was merged by someone else while waiting "
                        f"on checks; adopting its merge commit {sha[:8]}."
                    )
                    return {"merged": sha}
                # mergeCommit can lag the state flip; keep polling for the oid.
                print(f"PR #{pr_number} is MERGED; waiting for its merge commit oid...")
            elif state != "OPEN":
                print(f"PR #{pr_number} is {state}, not merging: {pr_url(repo, pr_number)}")
                return None
            else:
                verdict, blocker = checks_verdict(data)
                if verdict != last_verdict:
                    suffix = f" ({blocker})" if blocker else ""
                    print(f"PR #{pr_number} checks: {verdict}{suffix}")
                    last_verdict = verdict
                if verdict == "FAILURE":
                    print(
                        f"Check {blocker!r} failed on PR #{pr_number}; not merging: "
                        f"{pr_url(repo, pr_number)}"
                    )
                    return None
                if verdict == "SUCCESS":
                    head_sha = data.get("headRefOid")
                    if not head_sha:
                        print("Checks passed but no headRefOid was returned.")
                        return None
                    return {"head": head_sha}

        if time.time() >= deadline:
            break
        time.sleep(poll_seconds)

    print(f"Timed out waiting for checks on PR #{pr_number}: {pr_url(repo, pr_number)}")
    return None


def get_live_branch_sha(repo: str, branch: str) -> str | None:
    """Return the branch tip as the remote sees it right now (not the local clone)."""
    exit_code, stdout, stderr = run_command(
        ["gh", "api", f"repos/{repo}/git/ref/heads/{branch}", "-q", ".object.sha"]
    )
    if exit_code != 0 or not stdout.strip():
        print(f"Failed to read live {branch} tip: {stderr}")
        return None
    return stdout.strip()


def files_changed_between(repo: str, base_sha: str, head_sha: str) -> list[str] | None:
    exit_code, stdout, stderr = run_command(
        ["gh", "api", f"repos/{repo}/compare/{base_sha}...{head_sha}", "-q", ".files[].filename"]
    )
    if exit_code != 0:
        print(f"Failed to compare {base_sha[:8]}...{head_sha[:8]}: {stderr}")
        return None
    return [line for line in stdout.splitlines() if line]


def rebase_bump_branch(
    repo: str,
    branch: str,
    old_base_sha: str,
    new_base_sha: str,
    package_dir: str,
    files: list[str],
    headline: str,
    body: str,
) -> bool:
    """Rebuild the bump branch as a single signed commit on ``new_base_sha``.

    The bump commit is regenerated from the working-tree files rather than
    rebased with git, because only ``createCommitOnBranch`` produces a commit
    signed as the app. If the target branch's new commits touched the bumped
    files, the regenerated content would silently clobber them; if they
    touched anything else under ``package_dir``, the release would ship that
    code under a version and changelog computed before it existed. Both cases
    are refused and the job must be re-run to recompute the bump.

    Only the bump branch is ever force-moved here; the target branch is only
    ever fast-forwarded.
    """
    print(
        f"Target moved from {old_base_sha[:8]} to {new_base_sha[:8]}; "
        f"rebuilding {branch} on the new tip..."
    )
    changed = files_changed_between(repo, old_base_sha, new_base_sha)
    if changed is None:
        return False
    prefix = "" if package_dir in ("", ".") else package_dir.rstrip("/") + "/"
    overlap = sorted(
        path for path in changed if path in set(files) or path.startswith(prefix)
    )
    if overlap:
        print(
            f"Target branch changed files this bump depends on ({overlap}) since "
            "it was computed; refusing to rebuild. Re-run the job to recompute "
            "the bump."
        )
        return False

    exit_code, _, stderr = run_command(
        [
            "gh",
            "api",
            "-X",
            "PATCH",
            f"repos/{repo}/git/refs/heads/{branch}",
            "-f",
            f"sha={new_base_sha}",
            "-F",
            "force=true",
        ]
    )
    if exit_code != 0:
        print(f"Failed to move {branch} to {new_base_sha[:8]}: {stderr}")
        return False

    return create_signed_commit_on_branch(
        repo, branch, new_base_sha, files, headline=headline, body=body
    )


def fast_forward_target(repo: str, target_branch: str, head_sha: str) -> bool:
    """Fast-forward the target branch to ``head_sha`` with a strict ref update.

    ``force`` is deliberately absent: GitHub rejects a non-fast-forward
    update with 422, so a target branch that moved underneath us can never
    be overwritten.
    """
    print(f"Fast-forwarding {target_branch} to {head_sha[:8]} via REST refs API...")
    exit_code, _, stderr = run_command(
        [
            "gh",
            "api",
            "-X",
            "PATCH",
            f"repos/{repo}/git/refs/heads/{target_branch}",
            "-f",
            f"sha={head_sha}",
        ]
    )
    if exit_code != 0:
        print(f"Fast-forward of {target_branch} refused: {stderr.strip()[:300]}")
        return False
    print(
        f"{target_branch} fast-forwarded to {head_sha[:8]} by the release app. "
        "This direct ref update is the merge: the app is a bypass actor on the "
        "require-review ruleset, and GitHub honours app bypass only on direct "
        "ref updates, so no review appears on the PR."
    )
    return True


def verify_pr_merged(
    repo: str,
    pr_number: int,
    expected_sha: str,
    timeout_seconds: int = 120,
    poll_seconds: int = 5,
) -> str | None:
    """Confirm GitHub now reports the PR as MERGED at ``expected_sha``.

    Returns the merge commit SHA, or ``None`` if the PR does not reach
    MERGED within the window; the caller must not tag in that case.
    """
    print(f"Verifying PR #{pr_number} reports merged...")
    deadline = time.time() + timeout_seconds
    while True:
        data = read_pr(pr_number, "state,mergeCommit")
        if data is not None:
            state = data.get("state")
            if state == "MERGED":
                sha = (data.get("mergeCommit") or {}).get("oid")
                if not sha:
                    print("PR is MERGED but no mergeCommit oid was returned.")
                    return None
                if sha != expected_sha:
                    print(
                        f"PR #{pr_number} merged at {sha[:8]}, not the fast-forwarded "
                        f"head {expected_sha[:8]}; refusing to tag."
                    )
                    return None
                print(f"PR #{pr_number} merged at {sha[:8]}")
                return sha
            if state == "CLOSED":
                print(f"PR #{pr_number} is CLOSED, not MERGED: {pr_url(repo, pr_number)}")
                return None
        if time.time() >= deadline:
            break
        time.sleep(poll_seconds)

    print(
        f"PR #{pr_number} did not report MERGED within {timeout_seconds}s after the "
        f"fast-forward: {pr_url(repo, pr_number)}"
    )
    return None


def merge_bump_pr(
    repo: str,
    pr_number: int,
    branch: str,
    target_branch: str,
    base_sha: str,
    package_dir: str,
    files: list[str],
    headline: str,
    body: str,
    max_rounds: int = 3,
) -> str | None:
    """Land the bump PR by fast-forwarding the target branch as the release app.

    Each round: wait for green checks, confirm the live target tip is still
    the SHA the bump branch was built on, fast-forward, verify MERGED. If
    the target moved (seen by the guard, or by the strict fast-forward being
    refused inside the guard window), the bump branch is rebuilt on the new
    tip and the round repeats. A PR that someone else merged mid-wait is
    adopted as the merge. Returns the merged SHA, or ``None`` when the
    caller must not tag.
    """
    for round_number in range(1, max_rounds + 1):
        outcome = wait_for_checks(repo, pr_number)
        if outcome is None:
            return None
        if "merged" in outcome:
            return outcome["merged"]
        head_sha = outcome["head"]

        live_sha = get_live_branch_sha(repo, target_branch)
        if live_sha is None:
            return None
        if live_sha != base_sha:
            print(
                f"Strict fast-forward guard: {target_branch} is at {live_sha[:8]} but "
                f"the bump branch is based on {base_sha[:8]} (round {round_number}/{max_rounds})."
            )
            if round_number == max_rounds:
                print("Out of rebuild rounds; not merging.")
                return None
            if not rebase_bump_branch(
                repo, branch, base_sha, live_sha, package_dir, files, headline, body
            ):
                return None
            # The rebuilt head is seconds old. Wait for GitHub to settle it so
            # the next rollup read reflects the new commit; checks_verdict
            # treats an unregistered rollup as pending, so the rebuilt commit
            # cannot merge before Actions reports on it either way.
            if not wait_for_pr_stable(pr_number):
                return None
            base_sha = live_sha
            continue

        if fast_forward_target(repo, target_branch, head_sha):
            return verify_pr_merged(repo, pr_number, head_sha)

        # The strict (non-force) update was refused: the target moved inside
        # the guard window. Re-read the live tip on the next round and rebuild
        # there instead of aborting.
        print(
            f"Fast-forward refused mid-round; re-probing {target_branch} "
            f"(round {round_number}/{max_rounds})."
        )

    print("Out of merge rounds; not merging.")
    return None


def create_and_push_tag(repo: str, tag: str, sha: str) -> bool:
    """Create the tag on the remote pointing at ``sha`` and push it.

    ``sha`` must be a merged commit on the target branch: the tag publishes
    the release, so it may only ever point at a bump that actually landed.

    Uses the REST refs API rather than ``git push --tags`` so the operation
    works even if the runner's local main is behind (the workflow doesn't
    re-fetch after the fast-forward).
    """
    print(f"Creating tag {tag} at {sha[:8]} via REST refs API...")
    exit_code, _, stderr = run_command(
        [
            "gh",
            "api",
            f"repos/{repo}/git/refs",
            "-X",
            "POST",
            "-f",
            f"ref=refs/tags/{tag}",
            "-f",
            f"sha={sha}",
        ]
    )
    if exit_code != 0:
        # Only a genuine duplicate is tolerable. A bare 422 can also mean the
        # refs API has not seen the just-merged SHA yet; treating that as
        # success would report a release that never happened, and the branch
        # cleanup below it would then delete the recovery path.
        if "Reference already exists" in stderr:
            print(f"Tag {tag} already exists; publish already triggered.")
            return True
        print(f"Failed to create tag: {stderr}")
        return False
    print(f"Created tag {tag}")
    return True


def bump_package(
    package_name: str,
    package_dir: str,
    target_branch: str = "main",
    increment: str | None = None,
) -> bool:
    print(f"Starting version bump for {package_name} on {target_branch}...")

    if not Path(package_dir).exists():
        print(f"Error: package directory {package_dir} does not exist")
        return False

    configure_git()

    if not pull_branch(target_branch):
        return False

    repo = get_repo_slug()

    recovery = recover_untagged_bump(repo, package_name, package_dir)
    if recovery is not None:
        return recovery

    new_version = cz_bump_files_only(package_dir, package_name, increment)
    if new_version is None:
        return True
    branch = bump_branch_name(target_branch, package_name, new_version)
    tag = f"{new_version}-{package_name}"
    parent_sha = get_branch_sha(target_branch)

    modified = get_modified_files()
    if not modified:
        print("cz bump produced no file changes; nothing to commit.")
        return False
    print(f"Modified files: {modified}")

    if not create_remote_branch(repo, branch, parent_sha):
        return False

    headline = f"bump: {package_name} → {new_version}"
    body = f"Auto-bump for {package_name}."
    if not create_signed_commit_on_branch(
        repo, branch, parent_sha, modified, headline=headline, body=body
    ):
        return False

    pr_number = create_bump_pr(branch, target_branch, package_name, new_version)
    if pr_number is None:
        return False

    merge_sha = merge_bump_pr(
        repo,
        pr_number,
        branch,
        target_branch,
        parent_sha,
        package_dir,
        modified,
        headline,
        body,
    )
    if merge_sha is None:
        print(
            f"Bump PR {pr_url(repo, pr_number)} did not merge, so no "
            f"{tag} tag was created and nothing was released. Re-run this job "
            f"once the PR can merge to publish {package_name} {new_version}; if "
            "the PR has merged since, the re-run pushes the missing tag."
        )
        return False

    if not create_and_push_tag(repo, tag, merge_sha):
        return False

    delete_remote_branch(repo, branch)
    print(f"Successfully bumped {package_name} to {new_version}; tag {tag} pushed.")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Bump a package version via a PR fast-forwarded by the release app."
    )
    parser.add_argument("package_name", help="Package name (e.g. keycardai-oauth).")
    parser.add_argument("package_dir", help="Package directory (e.g. packages/oauth).")
    parser.add_argument(
        "--target-branch",
        default="main",
        help="Branch that receives the bump PR (default: main).",
    )
    parser.add_argument(
        "--increment",
        choices=("major", "minor", "patch"),
        help="Force a specific increment instead of deriving it from commits.",
    )
    args = parser.parse_args()

    if not bump_package(
        args.package_name,
        args.package_dir,
        target_branch=args.target_branch,
        increment=args.increment,
    ):
        print("Version bump failed")
        sys.exit(1)
    print("Version bump completed successfully")


if __name__ == "__main__":
    main()
